send-death-location:
  enabled: true
  message: "&e[Death Tracker] &fYou've just died at %d %d %d"
claim-keep-item:
  WILD: false
  UNTRUSTED: false
  TRUSTED: true
claim-keep-exp:
  WILD: false
  UNTRUSTED: false
  TRUSTED: true