survival:
  day:
    time: "0:12516"
    keep-item: true
    keep-exp: true
    broadcast:
      - "&a&lA new day starts! Items and exp are protected on death."
    sound: "ITEM_GOAT_HORN_SOUND_0"
    action-bar: "&a&lA new day starts! Items and exp are protected on death."

  night:
    time: "12516:24000"
    keep-item: false
    keep-exp: false
    broadcast:
      - "&a&lNight time! Items and exp are no longer protected on death."
    sound: "ITEM_GOAT_HORN_SOUND_0"
    action-bar: "&a&lNight time! Items and exp are no longer protected on death."

world_nether:
  default:
    keep-item: false
    keep-exp: false
