name: KeepMyLife
version: ${project.version}
main: dev.anhcraft.keepmylife.KeepMyLife
authors: [anhcraft]
depend: [CraftKit]
description: ${project.description}
website: https://anhcraft.dev/
api-version: "1.13"
