name: KeepMyLife
version: 1.2.6
main: org.anhcraft.keepmylife.KeepMyLife
authors: [anhcraft]
depend: [SpaciousLib]
loadafter: [DeathDropsAPI,SpaciousLib]
softdepend: [DeathDropsAPI]
description: A best plugin to keep player's items
website: https://anhcraft.org/