name: KeepMyLife
version: 1.3.6
main: org.anhcraft.keepmylife.KeepMyLife
authors: [anhcraft]
depend: [SpaciousLib]
loadafter: [DeathDropsAPI,SpaciousLib]
softdepend: [DeathDropsAPI]
description: The best plugin for keeping player's items
website: https://anhcraft.org/
api-version: 1.13
