name: KeepMyLife
version: 1.2.3
main: org.anhcraft.keepmylife.KeepMyLife
authors: [anhcraft]
depend: [SpaciousLib]
loadafter: [DeathDropsAPI,SpaciousLib]
softdepend: [DeathDropsAPI]
description: Keep your life with KeepMyLife plugin
website: https://anhcraft.org/